version: '3.1'
services:
  canvas:
    image: lairtonlelis/canvas-docker:latest
    environment:
      RAILS_PORT: 4000
      PORT: 4000
    ports:
      - 4000:4000
  caddy:
    image: "abiosoft/caddy:latest"
    volumes:
      - ./data/caddy/certs:/root/certs # to sync mkcert certificates to Caddy
      - ./data/caddy/Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "443:2015"
    depends_on:
     - canvas

networks:
  default:
    external:
      name: docker-local
